name: Thunderstore Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
          
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build . --configuration Release /p:PackageOutputPath=../ReleaseOutput /p:OutputPath=../ReleaseOutput

    - name: Install TCLI
      run: dotnet tool install --global tcli

    - name: Publish to thunderstore.io
      run: tcli publish --token ${{ secrets.TCLI_AUTH_TOKEN }} --config-path ./thunderstore.toml
